imports:
  - { resource: 'grids/api/product.yml' }

  - { resource: 'grids/backend/article.yml' }
  - { resource: 'grids/backend/article_for_product.yml' }
  - { resource: 'grids/backend/article_review.yml' }
  - { resource: 'grids/backend/contact_request.yml' }
  - { resource: 'grids/backend/customer.yml' }
  - { resource: 'grids/backend/customer_group.yml' }
  - { resource: 'grids/backend/dealer.yml' }
  - { resource: 'grids/backend/dealer_price.yml' }
  - { resource: 'grids/backend/game_play.yml' }
  - { resource: 'grids/backend/not_found_page.yml' }
  - { resource: 'grids/backend/person.yml' }
  - { resource: 'grids/backend/post.yml' }
  - { resource: 'grids/backend/product.yml' }
  - { resource: 'grids/backend/product_association_type.yml' }
  - { resource: 'grids/backend/product_list.yml' }
  - { resource: 'grids/backend/product_box.yml' }
  - { resource: 'grids/backend/product_review.yml' }
  - { resource: 'grids/backend/product_variant.yml' }
  - { resource: 'grids/backend/redirection.yml' }
  - { resource: 'grids/backend/root_taxon.yml' }
  - { resource: 'grids/backend/taxon_from_root.yml' }
  - { resource: 'grids/backend/topic.yml' }

  - { resource: 'grids/frontend/game_library.yml' }
  - { resource: 'grids/frontend/game_play.yml' }
  - { resource: 'grids/frontend/game_play_from_author.yml' }
  - { resource: 'grids/frontend/most_played.yml' }
  - { resource: 'grids/frontend/person.yml' }
  - { resource: 'grids/frontend/person_from_taxon.yml' }
  - { resource: 'grids/frontend/product.yml' }
  - { resource: 'grids/frontend/product_list_item.yml' }
  - { resource: 'grids/frontend/user_game_library.yml' }

sylius_grid:
    templates:
        action:
            default: "@SyliusUi/Grid/Action/default.html.twig"
            create: "@SyliusUi/Grid/Action/create.html.twig"
            delete: "@SyliusUi/Grid/Action/delete.html.twig"
            show: "@SyliusUi/Grid/Action/show.html.twig"
            update: "@SyliusUi/Grid/Action/update.html.twig"
            apply_transition: "@SyliusUi/Grid/Action/applyTransition.html.twig"
            links: "@SyliusUi/Grid/Action/links.html.twig"
            archive: "@SyliusUi/Grid/Action/archive.html.twig"

            create_product: "backend/product/grid/action/createProduct.html.twig"
            manage_articles: "backend/product/grid/action/manageArticles.html.twig"
            manage_article_reviews: "backend/article/grid/action/manageReviews.html.twig"
            manage_variants: "backend/product/grid/action/manageVariants.html.twig"
            create_taxon_for_parent: "backend/taxon/grid/action/createForParent.html.twig"
            list_posts: "backend/topic/grid/action/posts.html.twig"
            list_taxons: "backend/taxon/grid/action/taxons.html.twig"
            update_product_variant_positions: "backend/product_variant/grid/action/updatePositions.html.twig"
        filter:
            string: "backend/grid/filter/string.html.twig"
            boolean: "backend/grid/filter/boolean.html.twig"
            date: "@SyliusUi/Grid/Filter/date.html.twig"
            entity: "@SyliusUi/Grid/Filter/entity.html.twig"
            money: "@SyliusUi/Grid/Filter/money.html.twig"
            exists: "@SyliusUi/Grid/Filter/exists.html.twig"

            age: 'frontend/grid/filter/age.html.twig'
            duration: 'frontend/grid/filter/duration.html.twig'
            status: "backend/grid/filter/status.html.twig"
            player_count: 'frontend/grid/filter/playerCount.html.twig'
            taxon: "backend/grid/filter/taxon.html.twig"
