sylius_grid:
    grids:
        sylius_frontend_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments:
                            locale: "%locale%"
                            onlyPublished: true
                            criteria: "expr:service('request_stack').getCurrentRequest().get('criteria', [])"
            limits: ~
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: string
                    sortable: ~
                averageRating:
                    type: string
                    sortable: ~
                variant.releasedAt:
                    path: variant.releasedAt
                    type: string
                    sortable: ~
            filters:
                playerCount:
                    type: between_two_fields
                    options:
                        fields:
                            first: minPlayerCount
                            second: maxPlayerCount
                    form_options:
                        label: 'app.ui.player_count'
                minAge:
                    type: less_than_or_equal
                    form_options:
                        label: 'app.ui.age'
                        placeholder: 'Pouvant être joué à (en année)'
                minDuration:
                    type: less_than_or_equal
                    form_options:
                        label: 'app.ui.duration'
                        placeholder: 'Durée inférieure à (en minute)'
